// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-oFrcTCrvhyHk3LaK2tjd7KIljKOZtrY',
    appId: '1:477531377285:web:338b3ba5032a1952c923ec',
    messagingSenderId: '477531377285',
    projectId: 'mathmagic-1fed2',
    authDomain: 'mathmagic-1fed2.firebaseapp.com',
    storageBucket: 'mathmagic-1fed2.appspot.com',
    measurementId: 'G-F1KJTRF59T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHg6SoPHk2RMvrW6vwyl6Nu-1_PoPqpY',
    appId: '1:477531377285:android:cbb3a8b467bb244dc923ec',
    messagingSenderId: '477531377285',
    projectId: 'mathmagic-1fed2',
    storageBucket: 'mathmagic-1fed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFuuXNd3eDXU82r0nr2KCQGjthrZtg7I',
    appId: '1:477531377285:ios:e9c4a0f95d3a7805c923ec',
    messagingSenderId: '477531377285',
    projectId: 'mathmagic-1fed2',
    storageBucket: 'mathmagic-1fed2.appspot.com',
    androidClientId: '477531377285-do6ejslu80e2vafps85amtl9mlcj53ue.apps.googleusercontent.com',
    iosClientId: '477531377285-fecob3r1568s7erotnjmbn4c0r0oso1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlFuuXNd3eDXU82r0nr2KCQGjthrZtg7I',
    appId: '1:477531377285:ios:e9c4a0f95d3a7805c923ec',
    messagingSenderId: '477531377285',
    projectId: 'mathmagic-1fed2',
    storageBucket: 'mathmagic-1fed2.appspot.com',
    androidClientId: '477531377285-do6ejslu80e2vafps85amtl9mlcj53ue.apps.googleusercontent.com',
    iosClientId: '477531377285-fecob3r1568s7erotnjmbn4c0r0oso1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.math',
  );
}
